### PR TITLE
docker-Makefile/dashboard: add BROKER_SSL parameter

### PR DESCRIPTION
**Pull request by fjmolinas**

### CODE REVIEW

**Comment by fjmolinas** [comment]
all green

**Comment by aabadie** [comment]
Sorry to bother you but I would split the commit in 2: one for the Makefile and one for Docker. You could also add an env in docker-compose.yml:

https://github.com/pyaiot/pyaiot/blob/a0b05f05e6185b39fddb8375238d08fbb82609c9/docker/docker-compose.yml#L17-L20

**Comment by fjmolinas** [comment]
Commits have been split.

**Comment by fjmolinas** [comment]
ping @aabadie

**Review by aabadie — APPROVED** [review]

**Pull request merged**
