### PR TITLE
Refactor applications argument parser

### PR DESCRIPTION
**Pull request by aabadie**
Another step towards less code duplication: this PR tries to only declare application specific parameters along with their implementation and keep common parameters (broker-port, broker-host, debug, config, etc) in a common place.

Depends on #15

### CODE REVIEW

**Comment by bergzand** [comment]
Depends on #15 right?

**Comment by aabadie** [comment]
> Depends on #15 right?

Yes, I forgot to add it on the initial comment.

**Comment by aabadie** [comment]
@bergzand, I'm also looking for some help in reviewing this one. If you have some ideas for a better design, don't hesitate to propose :)

**Comment by bergzand** [comment]
I'm still thinking about this one. My first approach to further reduce the code duplication would be to give a class a list of option dicts.
This way the whole `if not hasattr(); define()` lists could be reduced to an iterator (maybe provided as a classmethod or an staticmethod from a mixin class).
From an object oriented perspective I would also argue for including the options in the class that requires those options

I think it would be good as a final goal to have a single generic `application.py` which is only supplied with a class that needs to be started.

**Comment by aabadie** [comment]
> I think it would be good as a final goal to have a single generic application.py which is only supplied with a class that needs to be started.

Yes that sounds very interesting. This will also require extra arguments such as `--enable-coap`, `--enable-mqtt` etc ?

**Comment by bergzand** [comment]
> Yes that sounds very interesting. This will also require extra arguments such as --enable-coap, --enable-mqtt etc ?

More that the `application.py` could provide a generic starter to start a single application such that the current `run()` method from the gateway `application.py` files becomes something like
```

def run(gatewayClass, arguments=[]):
    """Start the CoAP gateway instance."""
    if arguments != []:
        sys.argv[1:] = arguments
    gatewayClass.parse_arguments()
    if not tornado.platform.asyncio.AsyncIOMainLoop().initialized():
        tornado.platform.asyncio.AsyncIOMainLoop().install()

    start_application(gatewayClass(keys, options=options),
                      port=options.coap_port, close_client=True)
```

Not yet meant as a generic way to start everything, but maybe this could reduce the different `application.py` files between the gateways to a single generic starter common between all gateways.

**Comment by aabadie** [comment]
> the application.py could provide a generic starter to start a single application such that the current run() method from the gateway application.py files becomes something like

+1 for that solution. Feel free to open a PR if you have time.

> this could reduce the different application.py files between the gateways to a single generic starter common between all gateways.

I was also thinking to such an improvement. I'm fine with your proposal.

**Comment by bergzand** [comment]
My proposal is taking a bit longer than expected. Lets get this one merged, code looks good.

I don't know if the CI already checked for pep8-issues with this PR though.

**Comment by aabadie** [comment]
> I don't know if the CI already checked for pep8-issues with this PR though.

I'll rebase first to be sure.

**Comment by aabadie** [comment]
The pep8 are not fixed, let's merge.

**Pull request merged**
